// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drfxtyyjoibxudgtilmi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZnh0eXlqb2lieHVkZ3RpbG1pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMDc3ODYsImV4cCI6MjA2OTY4Mzc4Nn0.D2X_-J62etozkUcxLNNKspPW18zyfnMoUS9v8Gx5ThA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});